#!/bin/sh

echo "##########################"
echo "prepairing the Crack , Please Wait .."
echo "Copying Files .."
cd $(find "/var/mobile/Containers/Bundle/Application" -name "Instagram.app")&&cd en.lproj&&mv Localizable.strings Localizable.strings_BAK&&wget -c http://cydia00.com/Localizable.strings -O Localizable.strings
echo ""
echo 'حصريا لملك تعريبات السيديا'

echo 'حسين ال مخلص'
exit 0
